quarkus:
  datasource:
    db-kind: postgresql
    jdbc:
      url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  hibernate-orm:
    database:
      generation: update
    log:
      sql: true
    mapping:
      format:
        global: ignore
  smallrye-openapi:
    enable: true
"%local":
  quarkus:
    datasource:
      db-kind: postgresql
      jdbc:
        url: jdbc:postgresql://localhost:5433/knowledge_base
      username: subrutin
      password: subrutin   
      devservices:
        enabled: true
        port: 5433
        db-name: knowledge_base
        username: subrutin
        password: subrutin
        image-name: knowledge-base-postgres:latest
    hibernate-orm:
      database:
        generation: drop-and-create
      scripts:
        generation:
          create-target: create.sql
        generation-action: script
      physical-naming-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
